const PDFDocument = require("pdfkit");

const generateDocumentReport = (family, documents, user) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a new PDF document
      const doc = new PDFDocument({ margin: 50 });

      // Buffer to store PDF data
      const chunks = [];

      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      // Header
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("FAMILY PORTAL", { align: "center" })
        .moveDown(0.3);

      doc.fontSize(16).text("Document Report", { align: "center" }).moveDown(0.5);

      // Family Info
      doc
        .fontSize(10)
        .font("Helvetica")
        .text(`Family: ${family.name}`, { continued: false })
        .text(`Generated by: ${user.name}`)
        .text(`Date: ${new Date().toLocaleDateString()}`)
        .moveDown(0.5);

      // Separator line
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke().moveDown(0.5);

      // Documents section
      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text(`Documents (${documents.length})`)
        .moveDown(0.3);

      if (documents.length === 0) {
        doc
          .fontSize(12)
          .font("Helvetica")
          .text("No documents found.")
          .moveDown();
      } else {
        documents.forEach((document, index) => {
            console.log(`Document ${index + 1} starts at Y: ${doc.y}`);
          // Check if new page is needed
          if (doc.y > 700) {
            doc.addPage();
          }

          doc
            .fontSize(12)
            .font("Helvetica-Bold")
            .text(`${index + 1}. ${document.name}`)
            .moveDown(0.2);

          doc
            .fontSize(10)
            .font("Helvetica")
            .text(`Category: ${formatCategory(document.category)}`, {
              indent: 20,
            })
            .text(
              `Uploaded: ${new Date(document.createdAt).toLocaleDateString()}`,
              { indent: 20 },
            )
            .text(`Uploaded by: ${document.uploadedBy?.name || "Unknown"}`, {
              indent: 20,
            });

          if (document.description) {
            doc.text(`Description: ${document.description}`, { indent: 20 });
          }

          if (document.tags && document.tags.length > 0) {
            doc.text(`Tags: ${document.tags.join(",")}`, { indent: 20 });
          }

          doc
            .text(`File Size: ${formatFileSize(document.fileSize)}`, {
              indent: 20,
            })
            .moveDown(0.5);

            console.log(`Document ${index + 1} ends at Y: ${doc.y}`); 
        });
      }

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

// Helper functions
const formatCategory = (category) => {
  return category
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};

const formatFileSize = (bytes) => {
  if (bytes < 1024) return bytes + " B";
  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + " KB";
  return (bytes / 1048576).toFixed(1) + " MB";
};

module.exports = { generateDocumentReport };
